### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [lagodinka/regExp#2]
### Добрый день!

Очень хорошая работа!

_Отлично_:
- Большинство проверок проходит валидация имени
- Полностью проходит базовые проверки валидация почтового ящика
- Полностью проходит проверку валидация телефона
- Большинство проверок проходит валидация url/ip
- Выполнено требование к веткам
- Заполнено README

___

### Надо исправить:
- Проходит невалидное имя, где часть имени состоит из однйо буквы: `Ян-я`
- Проходит такое ip, но не должно: `http://www.255.255.255.255`

### *Можно лучше:*
- Почтовый ящик может иметь одну точку в подряд (не в начале) в части до @: `my.site123@mail.ru`.
- Ссылка в README не кликабельная, что не очень удобно

---
**Важно:** после исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на *github.io*.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by mrprovoker** [comment]
Спасибо за правки. Теперь работа отличная.

---
Все пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*

**Comment by lagodinka** [comment]
Спасибо, мастер!
